### ISSUE TITLE
一个小提议

### ISSUE THREAD

**Issue by silence-tang** [lif314/NeRFs-CVPR2023#3]
感谢大佬的整理工作！
提个小意见：能否将每个会议中的nerf paper按照类别整理一下，在markdown的一开头列出所有类别，并超链接到下文中相应的版块，这样大家看起来比较清晰，能够更快找到自己想看的paper，而不需要慢慢往下翻了。

**Comment by lif314** [comment]
近期比较忙，善用Ctrl+F。

**Comment by lif314** [comment]
> 感谢大佬的整理工作！ 提个小意见：能否将每个会议中的nerf paper按照类别整理一下，在markdown的一开头列出所有类别，并超链接到下文中相应的版块，这样大家看起来比较清晰，能够更快找到自己想看的paper，而不需要慢慢往下翻了。


近期比较忙，善用Ctrl+F。
